---
- name: Ensure git is present
  package:
    name: git
    state: present

- name: Clone borgmatic docker repo
  git:
    repo: 'https://github.com/coaxial/docker-borgmatic'
    update: true
    dest: /opt/docker-borgmatic
    version: master
  notify: update borgmatic container

- name: Create borgmatic directories
  file:
    path: /opt/docker-borgmatic/{{ item }}
    state: directory
    mode: '0700'
    owner: root
    group: root
  with_items:
    - borgmatic
    - ssh
  notify: update borgmatic container

- name: Copy borg and borgmatic files
  copy:
    src: "files/{{ item.name }}"
    dest: "/opt/docker-borgmatic/borgmatic/{{ item.name }}"
    mode: "{{ item.mode | default(0400) }}"
    owner: root
    group: root
  with_items:
    - name: "{{ mailcow__ssh_key_name }}"
    - name: "{{ mailcow__ssh_key_name }}.pub"
    - name: passphrase
    - name: before-backup.sh
      mode: '0500'
    - name: failed-backup.sh
      mode: '0500'
  notify: update borgmatic container

- name: Copy known_hosts file
  copy:
    src: files/known_hosts
    dest: /opt/docker-borgmatic/ssh/known_hosts
    mode: 0400
    owner: root
    group: root
  when: not mailcow__skip_known_hosts
  notify: update borgmatic container

- name: Copy templates
  template:
    src: "templates/{{ item.name }}"
    dest: "/opt/docker-borgmatic/borgmatic/{{ item.name }}"
    mode: "{{ item.mode | default(0400) }}"
    owner: root
    group: root
  with_items:
    - name: config.yaml
    - name: .jobber
    - name: after-backup.sh
      mode: '0500'
  notify: update borgmatic container
